databases:
  - name: library
    #databaseName: library_production_nakz_9yas
    databaseName: library_production
    user: iulian
    #plan: Free

services:
  - type: web
    name: library
    domains:
      - library.onrender.com
    env: ruby
    plan: Free   #aici am ales planul Free dar put alege si alte planuri gen Starter care este 7$
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library
          property: connectionString
      - key: RAILS_MASTER_KEY
      
             

        sync: false
