databases:
  - name: library
    databaseName: library_production
    user: ilates@yahoo.com

services:
  - type: web
    name: library
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false