
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#development:
#  <<: *default
#  database: library_development

development:
  <<: *default
  database: library_development
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 1
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: localhost
  port: 5432
  
<<<<<<< HEAD

=======
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
#production:
#  <<: *default
#  database: library_production
#  username: library
#  password: <%= ENV["LIBRARY_DATABASE_PASSWORD"] %>

production:
  adapter: postgresql
  encoding: unicode
  #host: mydatabase-instance.crelb6c2608h.us-east-1.rds.amazonaws.com
  #database: library_production
  #pool: 5
  #username:  iulian
  #password: iuliiuli
  url: postgres://iulian:iuliiuli@mydatabase-instance.cwgrqsm7tgq2.eu-central-1.rds.amazonaws.com:5432/library_production2
  #url: postgres://iulian:mydatabase-instance.crelb6c2608h.us-east-1.rds.amazonaws.com/library_production_nakz_9yas
  #<<: *default
  #database: library_production
  #username: library
  #password: <%= ENV["LIBRARY_DATABASE_PASSWORD"] %>
  #url: <%= ENV["DATABASE_URL"] %>
  #url: postgres://iulian:ZyqB4y88pV2yTGQ04WkGDPMLWYMnneTY@dpg-ce942ncgqg418pajk71g-a.oregon-postgres.render.com/library_production_nakz_9yas
>>>>>>> d0e00e8d81b80a38ed826699417c1bada1953df5

test:
  <<: *default
  database: library_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1
